# Matrices and Matrix Operations

This function introduces various ways to create
matrices and how to use them in TensorFlow

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

Start a graph session

In [7]:
sess = tf.Session()

### Declaring matrices

Identity Matrix:

In [8]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


2x3 random norm matrix:

In [9]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[ 1.49489737 -0.09959523  0.76246232]
 [-1.76982796 -1.66654098 -0.0775257 ]]


2x3 constant matrix:

In [10]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


3x2 random uniform matrix:

In [11]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[ 0.3097651   0.17874026]
 [ 0.15742052  0.61204958]
 [ 0.07598233  0.25019872]]


## Convert an np array to Tensor
Create matrix from np array:

In [13]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### Matrix Operations

Matrix addition/subtraction:

In [17]:
print(sess.run(A+B))
print(sess.run(B-B))

[[ 3.01843739  3.40874314  5.45708323]
 [ 4.83775854  5.50063181  6.32748985]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Matrix Multiplication:

In [18]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


Matrix Transpose:

In [19]:
print(sess.run(tf.transpose(C)))

[[ 0.21324468  0.49913585  0.78007913]
 [ 0.02604437  0.52318323  0.02446294]]


Matrix Determinant:

In [20]:
print(sess.run(tf.matrix_determinant(D)))

-38.0


Matrix Inverse:

In [21]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


Cholesky Decomposition:

In [22]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Eigenvalues and Eigenvectors:  
We use `tf.self_adjoint_eig()` function, which returns two objects, first one is an array of eigenvalues, the second is a matrix of the eigenvectors.

In [17]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]
